import React from 'react'

export default function FooterExtension() {
  return (
    <div className="border-t border-gray-100 pt-8">
      <p className="px-10 text-left text-xs/relaxed text-gray-500">
        A GUEPARDO INVESTIMENTOS LTDA DISTRIBUI APENAS COTAS DE FUNDOS DE INVESTIMENTOS NO QUAL
        FAZ A GESTÃO. A GUEPARDO INVESTIMENTOS LTDA NÃO COMERCIALIZA NEM DISTRIBUI COTAS DE
        OUTROS FUNDOS OU QUALQUER OUTRO ATIVO FINANCEIRO. AS INFORMAÇÕES CONTIDAS NESSE WEBSITE
        SÃO DE CARÁTER EXCLUSIVAMENTE INFORMATIVO. NÃO CONSTITUEM QUALQUER TIPO DE 
        ACONSELHAMENTO, SUGESTÃO OU OFERTA DE INVESTIMENTO. TAMPOUCO SE TRATA DE ANÁLISE
        OU RELATÓRIO DE ANÁLISE, E NÃO SE DESTINA À PUBLICAÇÃO, DIVULGAÇÃO OU DISTRIBUIÇÃO
        A TERCEIROS. O GESTOR NÃO SE RESPONSABILIZA POR EVENTUAIS ERROS DE AVALIAÇÃO E OMISSÕES. O GESTOR NÂO SE RESPONSABILIZA POR USO QUALQUER FEITO, SEJA PELO RECEPTOR DAS OPINIÕES E INFORMAÇÕES AQUI CONTIDAS, SEJA POR TERCEIROS QUE EVENTUALMENTE VENHAM A ELAS TER ACESSO. TAMPOUCO O GESTOR SE RESPONSABILIZA POR EVENTUAIS PREJUÍZOS OU DANOS CAUSADOS PELA UTILIZAÇÃO DAS OPINIÕES E INFORMAÇÕES AQUI CONTIDAS. O RECEPTOR NÂO DEVE TOMAR DECISÕES DE INVESTIMENTO COM BASE NESSAS OPINIÕES E INFORMAÇÕES. O INVESTIDOR DEVE TOMAR SUAS PRÓPRIAS DECISÕES DE INVESTIMENTO.
        EM RELAÇÃO AOS FUNDOS APRESENTADOS, LEIA OS RESPECTIVOS PROSPECTOS E OS REGULAMENTOS 
        DOS FUNDOS ANTES DE INVESTIR. RENTABILIDADE PASSADA NÃO REPRESENTA GARANTIA DE RENTABILIDADE
        FUTURA. OS FUNDOS DE INVESTIMENTO NÃO CONTAM COM GARANTIA DO ADMINISTRADOR, DO GESTOR, 
        DE QUALQUER MECANISMO DE SEGURO OU FUNDO GARANTIDOR DE CRÉDITO (FGC). OS FUNDOS DO 
        GESTOR PODEM ESTAR EXPOSTOS A SIGNIFICATIVA CONCENTRAÇÃO EM ATIVOS DE RENDA VARIÁVEL COM 
        POUCOS EMISSORES. VERIFIQUE SE OS FUNDOS DE SEU INTERESSE UTILIZAM ESTRATÉGIAS COM 
        DERIVATIVOS COMO PARTE INTEGRANTE DE SUAS RESPECTIVAS POLÍTICAS DE INVESTIMENTO. 
        TAIS ESTRATÉGIAS, DA FORMA COMO SÃO ADOTADAS, PODEM RESULTAR EM PERDAS PATRIMONIAIS
        PARA SEUS QUOTISTAS, PODENDO INCLUSIVE ACARRETAR PERDAS SUPERIORES AO CAPITAL APLICADO
        E A CONSEQUENTE OBRIGAÇÃO DOS RESPECTIVOS COTISTAS DE APORTAR RECURSOS ADICIONAIS PARA
        COBRIR O PREJUÍZO DO FUNDO. VERIFIQUE SE OS FUNDOS ESTÃO AUTORIZADOS A REALIZAR 
        APLICAÇÕES EM ATIVOS FINANCEIROS NO EXTERIOR E CRÉDITO PRIVADO. AS RENTABILIDADES 
        PORVENTURA MENCIONADAS NÃO SÃO ISENTAS DE IMPOSTOS. PARA FUNDOS QUE PERSEGUEM A 
        MANUTENÇÃO DE UMA CARTEIRA DE LONGO PRAZO, NÃO HÁ GARANTIA DE QUE TERÃO O TRATAMENTO 
        TRIBUTÁRIO PARA FUNDOS DE LONGO PRAZO. VERIFIQUE SE A LIQUIDAÇÃO FINANCEIRA E CONVERSÃO 
        DOS PEDIDOS DE RESGATE DE QUALQUER DOS FUNDOS MENCIONADOS OCORREM EM DATA DIVERSA DO 
        RESPECTIVO PEDIDO. PARA AVALIAÇÃO DA PERFORMANCE DE UM FUNDO DE INVESTIMENTO, É 
        RECOMENDÁVEL A ANÁLISE DE, NO MÍNIMO, 12 (DOZE) MESES. OUVIDORIA GUEPARDO 
        INVESTIMENTOS – (11) 3103-9200 – EMAIL:CONTATO@GUEPARDOINVEST.COM.BR
      </p>
    </div>
  )
}
